In [1]:
import torch 
from torch import nn  
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
class Lizard:
    def __init__(self, name):
        self.name = name   

    def set_name(self, name):
        self.name = name  

lizard = Lizard("Deep") 
print(lizard.name)
print("-------------------------------------") 
lizard.set_name("Lizard")
print(lizard.name)

Deep
-------------------------------------
Lizard


<h3> Build a Neural Network in Pytorch </h3>
<p> Extend the nn.Module based class </p><br>
<p> Define Layer as Class Attribute </p> <br>
<p> Implement the forward() methods </p>

In [3]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()

        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5) 
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5) 
        self.fc1 = nn.Linear(12*4*4, 120)
        self.fc2 = nn.Linear(120, 60)
        self.out = nn.Linear(60, 10)


    def forward(self, L):
        return L 

In [4]:
network = Network()
network 

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [5]:
network.conv1 

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [6]:
network.conv1.weight

Parameter containing:
tensor([[[[-0.0939,  0.0048, -0.1999,  0.0968,  0.0077],
          [-0.0649, -0.1726, -0.1477,  0.0036, -0.1025],
          [ 0.0193,  0.0098, -0.0959,  0.1758,  0.0541],
          [ 0.0255, -0.1558, -0.0982,  0.1168,  0.1888],
          [-0.1657, -0.0571, -0.0172,  0.1798, -0.1622]]],


        [[[-0.1264, -0.1943, -0.0878,  0.0592, -0.0752],
          [-0.0039, -0.1530,  0.1580, -0.0319,  0.1512],
          [-0.1146, -0.0404, -0.1269, -0.1491, -0.0676],
          [-0.1278, -0.1200, -0.1024, -0.1345, -0.0508],
          [-0.0299,  0.0596, -0.1516, -0.1063, -0.0867]]],


        [[[ 0.1756, -0.0289,  0.1422,  0.1002,  0.0533],
          [-0.0532,  0.1029, -0.0226, -0.1996, -0.1043],
          [-0.0711,  0.0916,  0.0417,  0.0202, -0.1231],
          [-0.0339, -0.0727,  0.1914,  0.0345,  0.0618],
          [-0.1503,  0.0382, -0.0398,  0.1288,  0.0458]]],


        [[[-0.0550,  0.1844,  0.0311, -0.1939,  0.0004],
          [-0.1149, -0.1934, -0.1549,  0.1055,  0.0998

In [7]:
network.conv1.bias

Parameter containing:
tensor([-0.1401,  0.0535,  0.0093, -0.0567, -0.0476, -0.1650],
       requires_grad=True)

In [8]:
network.conv1.weight.shape


torch.Size([6, 1, 5, 5])

In [9]:
torch.cuda.is_available()

True

In [10]:
network.parameters()

<generator object Module.parameters at 0x000001FFC99B5740>

In [11]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [12]:
for name, param in network.named_parameters():
    print(name,  '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


In [13]:
in_features = torch.Tensor([1, 2, 3, 4])


In [14]:
in_features.type(torch.float64) 

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [15]:
in_features.type(torch.float32) 

tensor([1., 2., 3., 4.])

In [16]:
weight_matrix = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [17]:
weight_matrix.dtype 

torch.float32

In [18]:
weight_matrix.matmul(in_features)

tensor([ 30.,  70., 110.])

<h3> Convolutional Neural Network </h3>

In [23]:
class CNN(nn.Module):
    def __init__(self, classes):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3)
        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3) 
        self.relu = nn.ReLU() 

        self.linear = nn.Sequential(
            nn.Dropout(0.2),
            nn.Linear(128*28*28, 512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, classes)
        )


    def forward(self, X):
        x = self.conv1(X)
        x = self.relu(x) 
        x = self.conv2(x)
        x = self.relu(x) 
        x = self.conv3(x)
        x = self.relu(x)
        x = x.view(x.size(0), -1)
        x = self.linear(x) 
        return x 

In [22]:
cnn = CNN(10) 
print(cnn)

CNN(
  (conv1): Conv2d(1, 32, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(5, 5), stride=(1, 1))
  (relu): ReLU()
  (linear): Sequential(
    (0): Dropout(p=0.2, inplace=False)
    (1): Linear(in_features=100352, out_features=512, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [24]:
class CNN(nn.Module):
    def __init__(self, classes):
        super(CNN, self).__init__()

        self.conv = nn.Sequential(
        nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3),
        nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3),
        nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3), 
        nn.ReLU() 
        )

        self.linear = nn.Sequential(
            nn.Dropout(0.2),
            nn.Linear(128*28*28, 512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, classes)
        )


    def forward(self, X):
        x = self.conv(X)
        x = x.view(x.size(0), -1)
        x = self.linear(x) 
        return x 
    

cnn = CNN(10) 
print(cnn)

CNN(
  (conv): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
    (1): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
    (2): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
    (3): ReLU()
  )
  (linear): Sequential(
    (0): Dropout(p=0.2, inplace=False)
    (1): Linear(in_features=100352, out_features=512, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [27]:
for name, param in cnn.named_parameters():
    print(name,  '\t\t', param.shape)

conv.0.weight 		 torch.Size([32, 1, 3, 3])
conv.0.bias 		 torch.Size([32])
conv.1.weight 		 torch.Size([64, 32, 3, 3])
conv.1.bias 		 torch.Size([64])
conv.2.weight 		 torch.Size([128, 64, 3, 3])
conv.2.bias 		 torch.Size([128])
linear.1.weight 		 torch.Size([512, 100352])
linear.1.bias 		 torch.Size([512])
linear.4.weight 		 torch.Size([10, 512])
linear.4.bias 		 torch.Size([10])
