In [1]:
import torch 
from torch import nn  
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
class Lizard:
    def __init__(self, name):
        self.name = name   

    def set_name(self, name):
        self.name = name  

lizard = Lizard("Deep") 
print(lizard.name)
print("-------------------------------------") 
lizard.set_name("Lizard")
print(lizard.name)

Deep
-------------------------------------
Lizard


<h3> Build a Neural Network in Pytorch </h3>
<p> Extend the nn.Module based class </p><br>
<p> Define Layer as Class Attribute </p> <br>
<p> Implement the forward() methods </p>

In [3]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()

        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5) 
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5) 
        self.fc1 = nn.Linear(12*4*4, 120)
        self.fc2 = nn.Linear(120, 60)
        self.out = nn.Linear(60, 10)


    def forward(self, L):
        return L 

In [5]:
network = Network()
network 

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [6]:
network.conv1 

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [7]:
network.conv1.weight

Parameter containing:
tensor([[[[ 0.1194,  0.1899,  0.1720,  0.0109,  0.1669],
          [-0.0862,  0.0985, -0.0233,  0.0191, -0.1847],
          [-0.1793,  0.0662,  0.0458,  0.0893, -0.0311],
          [ 0.1546,  0.1016,  0.1553,  0.1439,  0.1291],
          [ 0.1412, -0.0460,  0.0068, -0.1888, -0.0641]]],


        [[[ 0.0267,  0.0198, -0.0570,  0.0555, -0.0980],
          [-0.1666, -0.1127, -0.1393, -0.1081,  0.1121],
          [ 0.1969,  0.1235, -0.0228,  0.1864, -0.1245],
          [-0.0901, -0.0899,  0.0838, -0.1596,  0.1615],
          [-0.1391,  0.0888,  0.0263, -0.0701, -0.0493]]],


        [[[ 0.0662, -0.0684, -0.0717, -0.0080,  0.1481],
          [ 0.1206,  0.0942,  0.0890, -0.1989,  0.0487],
          [ 0.1684, -0.0088, -0.0914,  0.1051, -0.0917],
          [ 0.0412,  0.0518, -0.0757,  0.0714, -0.0173],
          [-0.0456, -0.1296, -0.0110,  0.1111, -0.1298]]],


        [[[-0.1776,  0.0798, -0.0118,  0.0609, -0.0502],
          [-0.1272,  0.1685, -0.0487,  0.0914, -0.1464

In [8]:
network.conv1.bias

Parameter containing:
tensor([ 0.0084, -0.0791, -0.1162,  0.0518, -0.0557, -0.0806],
       requires_grad=True)

In [9]:
network.conv1.weight.shape


torch.Size([6, 1, 5, 5])

In [14]:
torch.cuda.is_available()

True

In [15]:
network.parameters()

<generator object Module.parameters at 0x000002E207806890>

In [16]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [18]:
for name, param in network.named_parameters():
    print(name,  '\t\t', param.shape)

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])


In [27]:
in_features = torch.Tensor([1, 2, 3, 4])


In [28]:
in_features.type(torch.float64) 

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [29]:
in_features.type(torch.float32) 

tensor([1., 2., 3., 4.])

In [30]:
weight_matrix = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [31]:
weight_matrix.dtype 

torch.float32

In [32]:
weight_matrix.matmul(in_features)

tensor([ 30.,  70., 110.])